# Generated by Django 6.1 on 2026-08-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_choice',
            new_name='role',
        ),
    ]
