# Generated by Django 6.1 on 2026-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(null=True, upload_to='images/')),
                ('food_name', models.CharField(max_length=50, null=True)),
                ('food_price', models.FloatField(default=0)),
                ('food_availabity', models.BooleanField(default=False)),
                ('categories', models.CharField(blank=True, choices=[('veg', 'veg'), ('non-veg', 'non-veg')], max_length=20, null=True)),
                ('food_category', models.CharField(blank=True, choices=[('Soup', 'Soup'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Rolls', 'Rolls'), ('Cakes', 'Cakes'), ('Drinks', 'Drinks'), ('Milk Shake', 'Milk Shake'), ('Fride Rice', 'Fride Rice'), ('Fride Noodles', 'Fride Noodles'), ('Sandwich', 'Sandwich'), ('Ice Cream', 'Ice Cream'), ('Variety Rice', 'Variety Rice')], max_length=30, null=True)),
            ],
        ),
    ]
