# Generated by Django 6.1 on 2026-08-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_order_payment_id_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Food.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Food.order')),
            ],
        ),
    ]
