# Generated by Django 6.1 on 2026-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
