# Generated by Django 6.1 on 2026-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0007_cart_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='food_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
