# Generated by Django 6.1 on 2026-08-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0008_myorders_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
