# Generated by Django 6.1 on 2026-08-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0009_alter_myorders_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Food.cart'),
        ),
    ]
