# Generated by Django 6.1 on 2026-08-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0010_myorders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorders',
            name='amount',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
