# Generated by Django 6.1 on 2026-08-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0011_myorders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.order'),
        ),
    ]
