# Generated by Django 6.1 on 2026-10-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0012_alter_myorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
